name: Run Python Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную через UI GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run script
        run: python habr.py
